### ISSUE TITLE
Integrate with Backend

### ISSUE THREAD

**Issue by jaeyp** [SanctuaryRefugeeHealth/sanctuary-patient-app#5]
### Description
Currently, the UI doesn't call the APIs. Once this is completed, users can check appointment list, create a new appointment, confirm/delete an existing appointment, and list messages was sent.

### Requirements
Connect app to Backend APIs and modify UI and object properties to fit response data

### To-Dos
- [ ] Connect dummy HTTP request methods in appointments.js with Backend api
- [ ] Modify object properties according to response data
- [ ] Support a pagination to appointments table in case we get the long list of it from server
- [ ] Put confirm/delete buttons and confirmation modal for a deletion to appointment detail page
- [ ] Create languages.js in constants including top 5 languages and apply it to related pages
- [ ] Minor UI polish related
